name: Issues notifications
description:
  Retrieves the list of user notifications and forward it to your favorite
  messaging platform
author: Francois Gerthoffert

branding:
  icon: clock
  color: orange

inputs:
  github_token:
    description: GitHub token with read access to the project and its issues/PRs
    required: true
  reasons:
    description:
      Comma-separated list of notification reasons to filter by (e.g., mention,
      assign). See
      https://docs.github.com/en/rest/activity/notifications?apiVersion=2022-11-28#about-github-notifications
      for the full list of reasons.
    default: 'mention,assign'
    required: true

outputs:
  message:
    description: Formatted message listing all notifications

runs:
  using: node24
  main: dist/index.js
