name: Issues notifications
description:
  Retrieves the list of user notifications and forward it to your favorite
  messaging platform
author: Francois Gerthoffert

branding:
  icon: clock
  color: orange

inputs:
  github_token:
    description: GitHub token with read access to the project and its issues/PRs
    required: true
  reasons:
    description:
      Comma-separated list of notification reasons to filter by (e.g., mention,
      assign). See
      https://docs.github.com/en/rest/activity/notifications?apiVersion=2022-11-28#about-github-notifications
      for the full list of reasons.
    default: 'mention,assign'
    required: false
  message_style:
    description:
      The style of the formatted message output. Use 'slack' for
      Slack-compatible formatting with emojis and links, or 'raw' for plain
      text.
    default: 'slack'
    required: false
  max_notifications:
    description:
      Maximum number of notifications to include in the message. Set to 0 or
      leave empty to include all notifications.
    default: '0'
    required: false
  notification_action:
    description:
      Action to perform on processed notification threads. Use 'none' to do
      nothing (default), 'read' to mark as read, or 'done' to mark as done.
    default: 'none'
    required: false

outputs:
  message:
    description: Formatted message listing all notifications

runs:
  using: node24
  main: dist/index.js
